---
apiVersion: batch/v1
kind: Job
metadata:
  name: abapp
  labels:
    app: abapp
spec:
  template:
    spec:
      containers:
      - name: abapp
        image: vaibhav2016/ab:v1.0
        env:
        - name: con
          value: "5"
        - name: req
          value: "1000"
        - name: url
          value: "http://winapp:80/api/test"
      restartPolicy: Never
      nodeSelector:
        beta.kubernetes.io/os: linux
        beta.kubernetes.io/arch: amd64